# Generated by Django 4.1.6 on 2023-02-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reservation_date', models.DateTimeField(default=None)),
                ('type', models.CharField(choices=[('Beard', 'Beard Shaving'), ('Head', 'Head Shaving'), ('Waxing', 'Waxing'), ('Head massage', 'Head Massage')], default='Head', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
