# Generated by Django 4.1.6 on 2023-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaweapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type1',
            field=models.CharField(choices=[('Beard', 'Beard Shaving'), ('Head', 'Head Shaving'), ('Waxing', 'Waxing'), ('Head massage', 'Head Massage')], default='Head', max_length=30),
        ),
    ]
