# Generated by Django 4.1.6 on 2023-02-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaweapi', '0002_reservation_type1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type2',
            field=models.CharField(choices=[('Beard', 'Beard Shaving'), ('Head', 'Head Shaving'), ('Waxing', 'Waxing'), ('Head massage', 'Head Massage')], default='Head', max_length=30, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type3',
            field=models.CharField(choices=[('Beard', 'Beard Shaving'), ('Head', 'Head Shaving'), ('Waxing', 'Waxing'), ('Head massage', 'Head Massage')], default='Head', max_length=30, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=None, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('Beard', 'Beard Shaving'), ('Head', 'Head Shaving'), ('Waxing', 'Waxing'), ('Head massage', 'Head Massage')], default='Head', max_length=30, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type1',
            field=models.CharField(choices=[('Beard', 'Beard Shaving'), ('Head', 'Head Shaving'), ('Waxing', 'Waxing'), ('Head massage', 'Head Massage')], default='Head', max_length=30, verbose_name='Тип услуги'),
        ),
    ]
